
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  # name: {{ $fullName }} .Value.fullname
  # labels:
  #   app.kubernetes.io/name: {{ include "starter-kit.name" . }}
  #   helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
annotations:
    ingress.bluemix.net/appid-auth: {{ printf "bindSecret=%s namespace=%s requestType=%s serviceName=%s" (required "AppId binding is required to enable auth on the ingress" .Values.appidBinding) $namespace $requestType $fullName }}
spec:
  tls:
    - hosts:
        - {{ include "starter-kit.host" . }}
      secretName: {{ include "starter-kit.tlsSecretName" . }}
  rules:
    - host: {{ include "starter-kit.host" . }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
